version: '3'
services:
  face-detection: 
    image: 'millenia911/face-det:v1'
    volumes:
      - ./mirror_volume:/app/mirror
    ports:
      - 8080:8080
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure

  front-end: 
    image: 'millenia911/face-det-web:v1'
    volumes:
      - ./mirror_volume:/app/mirror
    ports:
      - 5000:5000
    deploy:
      restart_policy:
        condition: on-failure